export const project = {
  name: 'project',
  title: '设计作品',
  type: 'document',
  fields: [
    { name: 'title', title: '项目名称', type: 'string', validation: (Rule: any) => Rule.required() },
    { name: 'slug', title: 'URL别名', type: 'slug', options: { source: 'title' }, validation: (Rule: any) => Rule.required() },
    { name: 'coverImage', title: '封面图片', type: 'image', options: { hotspot: true } },
    { name: 'heroVideo', title: '项目视频', type: 'file' },
    { name: 'city', title: '城市', type: 'string' },
    { name: 'area', title: '面积', type: 'string' },
    { name: 'budgetRange', title: '预算区间', type: 'string' },
    { name: 'spaceType', title: '空间类型', type: 'string', options: { list: ['private_garden', 'villa_garden', 'terrace', 'roof_garden', 'balcony', 'flower_bed'] } },
    { name: 'styleTags', title: '风格标签', type: 'array', of: [{ type: 'string' }] },
    { name: 'shortDescription', title: '简短描述', type: 'text' },
    { name: 'designBackground', title: '设计背景', type: 'text' },
    { name: 'painPoints', title: '痛点问题', type: 'text' },
    { name: 'solution', title: '解决方案', type: 'text' },
    { name: 'plants', title: '植物配置', type: 'text' },
    { name: 'materials', title: '材料工艺', type: 'text' },
    { name: 'lighting', title: '灯光设计', type: 'text' },
    { name: 'beforeImages', title: '改造前图片', type: 'array', of: [{ type: 'image' }] },
    { name: 'afterImages', title: '改造后图片', type: 'array', of: [{ type: 'image' }] },
    { name: 'gallery', title: '图库', type: 'array', of: [{ type: 'image' }] },
    { name: 'clientFeedback', title: '客户评价', type: 'text' },
    { name: 'featured', title: '首页精选', type: 'boolean', initialValue: false },
    { name: 'sortOrder', title: '排序', type: 'number' },
  ],
}